### ISSUE TITLE
Docker Compose microservices

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv-microservices#11]
As a result of issues #3 and #8, each service will have a Docker file. Write a Docker compose file to orchestrate the deployment and inter-communication of the services.

**Comment by alancleary** [comment]
Added Docker Compose files in commit eb15055297bee61989aa61bdae4d29a3fb8f5d8e. @nathanweeks Mind taking a look to make sure everything is ship shape? The client is going to be run via its own Docker file for the time being, and I'm exposing the gRPC ports in addition to the HTTP ports since I'm planning to switch the client to gRPC.

**Comment by nathanweeks** [comment]
There's currently no "db" service:
```
$ docker-compose up -d --build
ERROR: Service 'chado_to_redisearch' depends on service 'db' which is undefined.
```
Should there be one (at least initially), as with gcv?

**Comment by alancleary** [comment]
Good catch (I don't actually have docker-compose installed...). As part of issue #10 we're moving away from depending on Chado, that is, data can be loaded from a Chado database or directly from GFF. Perhaps the chado_to_redisearch service should be renamed db and the chado_to_redisearch and gff_to_redisearch scripts can be run from within the container of via docker (compose) flags. @nathanweeks Do you know if that sort of arrangement is possible?

**Comment by adf-ncgr** [comment]
@alancleary do you mean (something like) the docker-compose up would utilize either chado_to_redisearch OR gff_to_redisearch depending on some condition (like whether it found an environment variable specifying a directory to mount for access to GFF data)?

**Comment by alancleary** [comment]
@adf-ncgr Yes, but it wouldn't be so smart; it would just run the database and not load any data unless you told it to and how.

**Comment by nathanweeks** [comment]
After #10 is resolved, it seems we would have a "load_gff" service that loads some GFFs in a directory (or maybe executes shell scripts in the directory that execute some loading command(s) with relevant command-line options within the container).

But until #10 is resolved, it may be easiest to copy the GCV "db" service as-is (and immediately deprecate it) so that these microservices can be easily tested/deployed. If no chado dumps are placed in the docker-entrypoint-initdb.d directory, the database would be empty, but at least the startup would work.

**Comment by alancleary** [comment]
Issue #10 is part of this epic so I don't think an intermediate step is necessary. To move forward before the GFF loader is ready, I think we can just drop the chado_to_redisearch dependence on db and let it load directly from an existing Chado DB, i.e. whatever's defined in the environment variables. Or is there some Docker gotcha that prevents a container from interacting with other, possibly not containerized, applications?

**Comment by nathanweeks** [comment]
BTW, the macro_synteny_blocks service is also not starting... apparently missing a "required option". How should that be set in the Compose file?
```
$ docker-compose up -d --build
...
$ docker-compose ps
...
gcv-microservices_macro_synteny_blocks_1      python3 microservice.py          Exit 2
...
$ docker-compose logs macro_synteny_blocks
Attaching to gcv-microservices_macro_synteny_blocks_1
macro_synteny_blocks_1           | usage: microservice.py [-h] [--no-http] [--hhost HHOST] [--hport HPORT]
macro_synteny_blocks_1           |                        [--no-grpc] [--ghost GHOST] [--gport GPORT] [--rdb RDB]
macro_synteny_blocks_1           |                        [--rpassword RPASSWORD] [--rhost RHOST] [--rport RPORT]
macro_synteny_blocks_1           |                        --pairwiseaddr PAIRWISEADDR
macro_synteny_blocks_1           | microservice.py: error: the following arguments are required: --pairwiseaddr
$ grep ENTRYPOINT macro_synteny_blocks/Dockerfile
ENTRYPOINT ["python3", "microservice.py"]
```

**Comment by nathanweeks** [comment]
Regarding the lack-of-db service: it's certainly feasible to talk to an external db service, though deploying one is at least inconvenient for the purpose of development & testing. For those use cases, it might be worth at least providing a redis dump that could be used to load the redisearch instance in an automated fashion; e.g., I think plunking one in the redisearch `/data` directory before container start would work; this could be be baked into a development/testing redisearch container image, like:

```
FROM redislabs/redisearch:1.6.13
ADD https://location/of/my/dump.rdb
```

and then in the (development) docker-compose.yml:
```
  redisearch:
    # assuming the Dockerfile is at redisearch/Dockerfile
    build: redisearch
    healthcheck:
      test: "redis-cli ping"
```

**Comment by alancleary** [comment]
> the macro_synteny_blocks service is also not starting...

Whoops. That's my bad. I accidentally deleted the dependency when copy-pasting port code...

Regarding adding a db dump to the RediSearch service, I think it should be left to the user whether a dump is loaded or if one of the loading scripts are used. Either way, I'll update the compose files so that RediSearch is the service the microservices depend on, instead of the chado_to_redisearch service.

**Comment by alancleary** [comment]
Commit a3fcac2bcf4348312bc94d1829cae4221a664a75 updated the microservices in the Docker Compose files to depend on the RediSearch service instead of the chado_to_redisearch service. Also, the chado_to_redisearch service was moved to load_data Docker Compose files, which will also contain the GFF loader service when it's implemented. This way users can choose to load data only if they need to and pick which loading method they want to use.

**Comment by nathanweeks** [comment]
That should be good enough for now (though the "micro_synteny_blocks" service should be micro_synteny_search: https://github.com/legumeinfo/gcv-microservices/commit/736d7bfece6c5ccc16aa0c590458139af5ec3ad7 ).

Since now-removed chado_to_redisearch service depended on redisearch to be "healthy" (as opposed to simply started), it might be worth pushing that dependency to the microservice level (https://github.com/legumeinfo/gcv-microservices/commit/1fb62b94e1f82009a5c603740e0ee1dd5addbeeb), as it's a necessary condition for their functionality.

**Comment by alancleary** [comment]
Commit bde4b9410b364e19d5990b090453f3b49a1da8b5 added gRPC-Web support to the microservices by adding an Envoy Proxy configuration to the Docker Compose files. It also updated the microservices routers defined in the Docker Compose files to use paths instead of subdomains.

There's probably still a few Docker Compose related loose ends that need to be tied up but those can be handled in other issues as they come up. Closing.
