### ISSUE TITLE
Add proxy for microservices

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv-microservices#17]
The motivation for this is two-fold: 1) It would be nice if all microservices were available via the same port and 2) it's required to make gRPC requests from a web client using JavaScript/TypeScript (https://grpc.io/docs/languages/web/basics/).

**Comment by nathanweeks** [comment]
Could probably use Traefik for this (at least in the Docker Compose setup): https://doc.traefik.io/traefik/user-guides/grpc/

**Comment by nathanweeks** [comment]
...although in case it's more familiar and convenient, it seems [nginx can also handle gRPC](https://www.nginx.com/blog/nginx-1-13-10-grpc/)

**Comment by alancleary** [comment]
OK. I'm crying uncle on this one. I had everything working with Traefik and Docker Compose. Then, right before committing the configuration, I decided to use network names specific to GCV so I changed the network names and the whole thing broke (every endpoint throws a 502 with no useful logging from Traefik). Switching back to the old network names doesn't fix it either! I've tried restarting docker and forcing Docker Compose to rebuild its containers but, alas, it still doesn't work. I am stumped!

@nathanweeks Can you take a look at the config files and see if there's anything obvious I'm missing? I'm pretty sure it has something to do with how Traefik is wiring things up and my feeble understanding of Docker (Compose). The attached zip contains a directory with a docker-compose.yml file and a traefik.yml file. The prior goes in the root of the gcv-microservices repo and the latter goes in the proxy/ subdirectory of the gcv-microservices repo.

[https://app.zenhub.com/files/156288230/e5f5c3cd-d28d-48be-831a-7b94389b8000/download](https://app.zenhub.com/files/156288230/e5f5c3cd-d28d-48be-831a-7b94389b8000/download)

**Comment by nathanweeks** [comment]
I took a stab at a working docker-compose.yml [in the docker branch](https://github.com/legumeinfo/gcv-microservices/blob/docker/docker-compose.yml). It seemed to "work" for me via `docker-compose up --build -d` (though I don't have a suitable RDB file to test with, so I just verified the services could be accessed via, e.g., `curl -H 'Host: chromosome.gcv.localhost' http://localhost , and checked the traefik logs with `docker-compose logs reverse-proxy`; guidance on improvements to this incomplete approach would be appreciated!). A few observations/questions:

1. I assume you had created an [external](https://docs.docker.com/compose/compose-file/#external-1) network manually outside of docker-compose? That extra step might not be needed for a developer-friendly Compose file; to test network isolation between services, two separate bridge networks defined in the Compose file might suffice (and it's convenient to have any networks automatically created by `docker-compose up`, and blown away by `docker-compose down`.
    - minor personal preferencess: I specified the traefik configuration in the `command:` field for the service in docker-compose.yml, instead of a separate YAML file, as it's easier to track in one place, and seems like it could be preferable when deploying into production, as then one needn't worry about building a container image for traefik with its configuration included, or bind mounting it from the host, etc.; and I renamed the "insecure" entrypoint to "web", as the former appears to be used in other contexts in the Traefik docs.
2. It might be worth exploring path-based [routing rules](https://doc.traefik.io/traefik/routing/routers/#rule), as I assume an eventual production instance wouldn't use separate subdomains for each microservice.
3. (minor) Compose version 3 [depends_on](https://docs.docker.com/compose/compose-file/#depends_on) "no longer supports the `condition` form", (though since docker-compose 1.27.0, the version field is optional, so omitting it would have the positive side effect of enforcing a minimum docker-compose version).
4. I had previously added a `condition: service_healthy` to some of the services, though it may not be necessary (it looks like you added a defensive `await connection.ping()` to redis connection objects).

**Comment by alancleary** [comment]
Thanks for jumping on this @nathanweeks, and sorry it took so long to get back to you. The docker-compose.yml you pushed to the docker branch seems to be working. Regarding your observations/questions:

1. I did manually create the external network. I used an external network, rather than letting Docker Compose handle it, only because that's what all the tutorials I followed did. Your comment makes me think that manually creating the network is necessary in production. Is this true?
    - I see you configured Traefik to use the "traefik" docker network to communicate with containers. However, all the containers are on the default (gcv-microservices_default) and/or internal networks, not the traefik network. So how is this configuration working? See docs: https://doc.traefik.io/traefik/providers/docker/#network
2. Thanks for the link. I was planning to look into path-based routes after I got everything working. The tutorials I followed used subdomains so that's what I did for an initial configuration.
3. That all news to me. Thanks!
4. I think the "await connection.ping()" predates containerization of the services. Though it's now redundant, I think it's worth keeping since these microservices may still be used in a non-containerized environment.

**Comment by nathanweeks** [comment]
1. Whoops, `--providers.docker.network=traefik` was leftover copy/paste from another traefik Compose file that did use an external network. The [traefik documentation](https://doc.traefik.io/traefik/providers/docker/#network) states it "Defines a default docker network to use for connections to all containers". That network didn't exist on my workstation; perhaps traefik fell back to the "default" network that it's connected to (by default)?
4. I agree it's worth keeping, in case, e.g., these microservices get transplanted to a more distributed environment (even containerized, e.g., like Kubernetes) where there is no direct equivalent for `condition: service_healthy`

**Comment by alancleary** [comment]
Interestingly, `--providers.docker.network=traefik` doesn't work in my dev copy of the repo. However, setting it to the default network auto-generated by Docker Compose does the trick: `--providers.docker.network=gcv-microservices_default`. Unless there's a reason to use a Docker network created outside of Docker Compose in production (I suspect all the tutorials used an external network so they didn't have to deal with the prefix automatically added by Docker Compose) I think I'll stick to the networks created by Docker Compose.

**Comment by alancleary** [comment]
OK. I looked at the Traefik source code and found that if you don't specify what Docker network Traefik should use to communicate with containers then it will default to whatever Docker network the Traefik proxy's container is on. So if we designate the default network as the one Traefik will use to communicate with containers or explicitly set what network Traefik's container is on, then we don't have to explicitly set the docker network name in the Traefik configuration. This is advantageous because, as I previously mentioned, if the network is automatically created by Docker Compose then explicitly setting it in the Traefik configuration requires knowing the project name used by Docker Compose. Since the project name isn't easily accessible in `docker-compose.yml`, letting Traefik acquire the correct name via its container is a more portable solution.

**Comment by nathanweeks** [comment]
Wow, good spelunking. I had just [removed the `--providers.docker.network=traefik` option in the "docker" branch](https://github.com/legumeinfo/gcv-microservices/commit/d1fa1b621c1d07c96735209557392d8c9de76ae3), and it did appear to just work, but I'm glad to know there's an explanation for this. I agree with the preference for a simpler, portable, "just works" approach.

**Comment by alancleary** [comment]
Thanks. Unfortunately I'm still getting inconsistent results when there's multiple networks involved, i.e. a network for Traefik and an internal network for inter-service communication, regardless of whether I use the `--providers.docker.network` flag to disambiguate which network to use on containers with more than one network. Fortunately, removing all network configuration and letting everything run on the one default network automatically created by Docker Compose seems to consistently work. So I'm just going to push a compose that does that and leave best practices for the future. ¯\\\_(ツ)\_/¯

**Comment by alancleary** [comment]
The Traefik reverse proxy was added with a basic configuration in commit 383c1a609e1745010ff992d07729141a94d50265.
