### ISSUE TITLE
gff_to_redisearch: make --extend default, add --clear option

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv-microservices#19]
Given that the script only allows a single genome to be added to the db at a swoop, it seems to make more sense (opine @nathanweeks and @adf-ncgr) to append data as the norm. An explicit --clear option could provide the alternate (current default) behavior. This quibble aside, script seems to be doing the needful so far as we've been able to test in the current state of the rest of the containerized system.

**Comment by alancleary** [comment]
This was addressed for the Chado loader in commit b8596ed0b41f650cbb5cd58d5e4203e3c2d4815b, which combined the --reload and --extend flags into a single --load-type flag that allows users to specify how data should be loaded into RediSearch, i.e. "new", "reload", or "append".

This same solution will be applied to the GFF/FASTA loader in issue #24 when the two loading scripts are combined.

**Comment by alancleary** [comment]
This functionality was added for the GFF loaded in commit eaa2c396656a977723f18f34cee6d6b0e50444e7, which combined the Chado and GFF loaders into a single program.
