### ISSUE TITLE
aioredis v2 upgrade needed 

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv-microservices#32]
otherwise, we'll see at least this one error:
> Task exception was never retrieved
> future: <Task finished name='Task-1' coro=<main_coroutine() done,
> defined at /app/chromosome_region/__main__.py:74>
> exception=AttributeError("module 'aioredis' has no attribute
> 'create_redis_pool'")>
> Traceback (most recent call last):
>   File "/app/chromosome_region/__main__.py", line 75, in main_coroutine
>     redis_connection = await connectToRedis(args.rhost, args.rport,
> args.rdb, args.rpassword)
>   File "/app/chromosome_region/database.py", line 7, in connectToRedis
>     connection = await aioredis.create_redis_pool((host, port), db=db,
> password=password, encoding='utf-8')
> AttributeError: module 'aioredis' has no attribute 'create_redis_pool'

@alancleary says sticking with <2 is the non-preferred solution so we'll look at what's needed to get up to v2 compatibility.

**Comment by alancleary** [comment]
Done in commit 4dcada3a28e172fba8a20359b2eb153aa29ea323.
