### ISSUE TITLE
Update Redis schema

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv-microservices#9]
The services API has changed since the GCV microservices were implemented. This may or may not have implications for the schema of the Redis database on which these microservices depend. Reevaluate the schema and make any necessary changes. The chado_to_redis.py script should be updated as well if necessary.

**Comment by alancleary** [comment]
The annotation and strand fields were added to the RediSearch genes index in commit 60a953a910545b607266b02e36c33de45e74a1a9 to support the genes microservice.

**Comment by alancleary** [comment]
The length, genus, and species fields were added to the RediSearch chromosome index and the fmin field of the gene index was made sortable in commit 400a43de6aed274918a9b51fab2e0339ab6afbec.

**Comment by adf-ncgr** [comment]
We might want to consider adding "strain" and genome assembly version info too.

**Comment by alancleary** [comment]
@adf-ncgr Is this data available in Chado?

**Comment by adf-ncgr** [comment]
sort of, although I was thinking of it less from the perspective of chado than of stuff that could come out of flatfile metadata for the future loader. That is, I wouldn't make them "not-null" but it would be good to have a place to tuck this metadata rather than stuffing it into our yucky prefixes. See legumeinfo/gcv#148 for example

**Comment by alancleary** [comment]
I haven't finished updating the Redis schema yet but so far everything has ended up in RediSearch. Assuming you don't want to do any kind of searching/filtering of these data, you could store them as a chromosome document's [payload](https://oss.redislabs.com/redisearch/payloads/). This would allow for fast retrieval at no cost besides the cost to transfer the data. Perhaps this could be wrapped into [metadata epic](https://github.com/legumeinfo/gcv/issues/63), which has been open for a long time...

**Comment by adf-ncgr** [comment]
Yeah, it's not urgent I just figured as long as we were working on schema enhancements it might be appropriate to bring it up. I can imagine it being used for search/filtering in the same way that we now use filtering on the yucky prefixes, but that wasn't what I had in mind initially. As far as legumeinfo/gcv#63 is concerned, it would be fine to wrap it into that although my conception of that one was focused more on the genes and less on the genomes (this may be a distinction without a difference).

**Comment by alancleary** [comment]
The index field was, which tracks a gene's position on its chromosome, was added to the RediSearch genes index in commit a9b359141f1731c4fff0dfceeda25829552f46ac. The index field was made sortable and the fmin field was made not sortable in preference for the index field.

Also, the "-" character is now being escaped in chromosome, gene, and family names to prevent RediSearch from separating on the character when tokenizing. This was done because a chromosome name that contained a "-" wasn't being found during a verbatim search. At first I tried escaping all [RediSearch punctuation characters](https://oss.redislabs.com/redisearch/Escaping/), but this was causing fuzzy chromosome and gene searches to fail. @adf-ncgr do you know of any special characters besides "." and "-" that may be used in chromosome, gene, or family names? I'm definitely going to have to write some tests for this or rethink using RediSearch for exact matching of single strings containing special characters.

**Comment by adf-ncgr** [comment]
@alancleary you never know what might show up but I think the ones you have excluded are probably good for now assuming I read the linked document properly to say that underscores are non-problematic and that our region specifiers get subtracted out before the name searching is done. Will \ escaping get passed through if a user needs to deal with any very special cases?

**Comment by alancleary** [comment]
> Will \ escaping get passed through if a user needs to deal with any very special cases?

I haven't tested it but I think it should, yes.

It's hard to anticipate what chromosome/gene/family naming schemes might be used so I think the thing to do is make the set of escaped characters configurable and add a --verify flag to the loading script(s) that ensures all names can be recovered via verbatim search.

**Comment by alancleary** [comment]
Commit 6029ad393796da5bd9616f4cd02ac29b047b9fed removed (super) contigs from being loaded because they were bogging down the macro-synteny service.

**Comment by adf-ncgr** [comment]
> Commit [6029ad3](https://github.com/legumeinfo/gcv-microservices/commit/6029ad393796da5bd9616f4cd02ac29b047b9fed) removed (super) contigs from being loaded because they were bogging down the macro-synteny service.

@alancleary is this anticipated to be a temporary measure? being able to handle non-chromosomes is quite useful in some cases (though of course one can always game the system and just say everything is a chromosome). In any case we definitely will want to be able to include non-chromosomal in microsynteny views.

**Comment by alancleary** [comment]
@adf-ncgr I was hoping you would chime in on this. If you're OK with excluding all (super) contigs from macro-synteny, then I could tag whether "chromosome" in RediSearch is a chromosome or a contig and exclude the contigs from the macro-synteny services.

**Comment by adf-ncgr** [comment]
I thought you'd be dreading my chime! I guess in my ideal world, whether or not to exclude sequences from certain parts of the application based on their type would still be configurable by the service provider (and perhaps also an option in the client, though obviously they couldn't override what a provider enabled). But that could be a nice-to-have for future, since I don't want to bog you down with minutiae- sounds like you're making rapid progress on the epic!

**Comment by adf-ncgr** [comment]
PS. I should note that we do have a plan afoot to make more explicit what types our genomic sequences are in datastore files.

**Comment by alancleary** [comment]
Commit 1df5ae2ad355cd0dde531c8e3b57673111458872 followed through on the revelation in issue #14. Specifically, it updated the RediSearch document IDs to be the unique name of the entity the document represents. This allows specific documents to now be retrieved via ID, rather than performing a verbatim search, which required escaping certain special characters.

The commit also introduced ordered lists representing a chromosome's gene names, gene annotations, genes fmin values, and gene fmax values. Again, this was to accommodate retrieving these values (in order) for genes belonging to a specific chromosome without performing a (Redi)search. This has removed the chromosome loading bottleneck from the pairwise macro-synteny microservice (described in issue #8), bringing the total runtime of the macro-synteny request for Glycine max chromosome 15 down from 6 seconds to less than 2 seconds.

**Comment by alancleary** [comment]
The old Chado to Redis loading script was removed in commit 27c5baac6d809eb54190bdf4c36b7d191099d378.

**Comment by alancleary** [comment]
Commit 0a7e926e5219286fecaa7ea3656d21cf44f9f1b6 added a --unqiename flag to the Chado loading script that allows users to control whether chromosome and gene names are loaded from the name of uniquename field of the feature table in Chado.

**Comment by alancleary** [comment]
Though there are some additional revisions that could be made, the microservices are functional with the schema as is. Closing.
